/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'employee-basic-info'
const service = 'xbt-platform-salary-service'

export const EmployeeBasicInfoController = {
    // 查询全部
    getAll: {
        service,
        controller,
        path: '/api/employeeBasicInfo/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // 使用ID查询
    getById: {
        service,
        controller,
        path: '/api/employeeBasicInfo/getById/{id}',
        action: 'getById',
        type: RequestMethod.Get
    },
    // 分页查询
    query: {
        service,
        controller,
        path: '/api/employeeBasicInfo/query',
        action: 'query',
        type: RequestMethod.Get
    },
    // 同步员工基础信息
    syncAllEmployeeBasicInfo: {
        service,
        controller,
        path: '/api/employeeBasicInfo/syncAllEmployeeBasicInfo',
        action: 'syncAllEmployeeBasicInfo',
        type: RequestMethod.Put
    },
    // 同步单个员工
    syncOneEmployee: {
        service,
        controller,
        path: '/api/employeeBasicInfo/syncOneEmployee/{id}',
        action: 'syncOneEmployee',
        type: RequestMethod.Put
    },
    // 测试递归
    test: {
        service,
        controller,
        path: '/api/employeeBasicInfo/test',
        action: 'test',
        type: RequestMethod.Put
    },
    // 更新
    update: {
        service,
        controller,
        path: '/api/employeeBasicInfo/update/{id}',
        action: 'update',
        type: RequestMethod.Put
    },
    // 钉钉回调调用
    updateByDingTalkService: {
        service,
        controller,
        path: '/api/employeeBasicInfo/updateByDingTalkService/{id}',
        action: 'updateByDingTalkService',
        type: RequestMethod.Put
    },
    // 更新/增加员工身份证号码
    updateIdCard: {
        service,
        controller,
        path: '/api/employeeBasicInfo/updateIdCard/{id}',
        action: 'updateIdCard',
        type: RequestMethod.Put
    }
}
