/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'inner_reward'
const service = 'xbt-platform-salary-service'

export const Inner_rewardController = {
    // 申请
    apply: {
        service,
        controller,
        path: '/api/inner_reward/apply/{id}',
        action: 'apply',
        type: RequestMethod.Get
    },
    // 确认
    confirm: {
        service,
        controller,
        path: '/api/inner_reward/confirm',
        action: 'confirm',
        type: RequestMethod.Post
    },
    // create
    create: {
        service,
        controller,
        path: '/api/inner_reward/create',
        action: 'create',
        type: RequestMethod.Post
    },
    // delete
    delete: {
        service,
        controller,
        path: '/api/inner_reward/delete/{id}',
        action: 'delete',
        type: RequestMethod.Delete
    },
    // 驳回
    deny: {
        service,
        controller,
        path: '/api/inner_reward/deny',
        action: 'deny',
        type: RequestMethod.Post
    },
    // 导出待审批
    exportTodo: {
        service,
        controller,
        path: '/api/inner_reward/exportTodo',
        action: 'exportTodo',
        type: RequestMethod.Get
    },
    // get All
    getAll: {
        service,
        controller,
        path: '/api/inner_reward/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // 审批历史
    getAuditList: {
        service,
        controller,
        path: '/api/inner_reward/getAuditList/{id}/{fingerPrint}',
        action: 'getAuditList',
        type: RequestMethod.Get
    },
    // findOne
    get: {
        service,
        controller,
        path: '/api/inner_reward/getById/{id}',
        action: 'get',
        type: RequestMethod.Get
    },
    // 审批内容
    getAllConfirm: {
        service,
        controller,
        path: '/api/inner_reward/getEmployeeInnerReward/{id}',
        action: 'getAllConfirm',
        type: RequestMethod.Get
    },
    // get List
    getList: {
        service,
        controller,
        path: '/api/inner_reward/getList',
        action: 'getList',
        type: RequestMethod.Get
    },
    // 我的流程规则
    getMyFlowConfig: {
        service,
        controller,
        path: '/api/inner_reward/getMyFlowConfig',
        action: 'getMyFlowConfig',
        type: RequestMethod.Get
    },
    // 我的所有申请
    getMyList: {
        service,
        controller,
        path: '/api/inner_reward/getMyList',
        action: 'getMyList',
        type: RequestMethod.Get
    },
    // 我的审批流程
    getMySalaryConfirmFlow: {
        service,
        controller,
        path: '/api/inner_reward/getMySalaryConfirmFlow',
        action: 'getMySalaryConfirmFlow',
        type: RequestMethod.Get
    },
    // update
    update: {
        service,
        controller,
        path: '/api/inner_reward/update/{id}',
        action: 'update',
        type: RequestMethod.Put
    }
}
