/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'report'
const service = 'xbt-platform-salary-service'

export const ReportController = {
    // 导出列表
    exportAnalysis: {
        service,
        controller,
        path: '/api/report/exportAnalysis',
        action: 'exportAnalysis',
        type: RequestMethod.Post
    },
    // 导出审批记录
    exportAudit: {
        service,
        controller,
        path: '/api/report/exportAudit',
        action: 'exportAudit',
        type: RequestMethod.Post
    },
    // 导出列表
    exportDetail: {
        service,
        controller,
        path: '/api/report/exportDetail',
        action: 'exportDetail',
        type: RequestMethod.Post
    },
    // 导出个人总计
    exportEmployeeSummary: {
        service,
        controller,
        path: '/api/report/exportEmployeeSummary',
        action: 'exportEmployeeSummary',
        type: RequestMethod.Post
    },
    // 部门总计
    query: {
        service,
        controller,
        path: '/api/report/querySummary',
        action: 'query',
        type: RequestMethod.Post
    }
}
