/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'salaryvalue'
const service = 'xbt-platform-salary-service'

export const SalaryvalueController = {
    // calculation by employee
    calcByEmployee: {
        service,
        controller,
        path: '/api/salaryvalue/calcByEmployee/{employeeId}/{month}',
        action: 'calcByEmployee',
        type: RequestMethod.Get
    },
    // calculation by id
    calcById: {
        service,
        controller,
        path: '/api/salaryvalue/calcById/{id}',
        action: 'calcById',
        type: RequestMethod.Get
    },
    // create for employee
    create: {
        service,
        controller,
        path: '/api/salaryvalue/create/{employeeId}/{month}',
        action: 'create',
        type: RequestMethod.Get
    },
    // create for team
    create4team: {
        service,
        controller,
        path: '/api/salaryvalue/create4team/{teamId}/{month}',
        action: 'create4team',
        type: RequestMethod.Get
    },
    // create for rules
    createForRules: {
        service,
        controller,
        path: '/api/salaryvalue/createForRules',
        action: 'createForRules',
        type: RequestMethod.Post
    },
    // 核算列表
    getAll: {
        service,
        controller,
        path: '/api/salaryvalue/getAllSalaryValue',
        action: 'getAll',
        type: RequestMethod.Post
    },
    // findOne
    getByEmployee: {
        service,
        controller,
        path: '/api/salaryvalue/getByEmployee/{employeeId}/{month}',
        action: 'getByEmployee',
        type: RequestMethod.Get
    },
    // findOne
    get: {
        service,
        controller,
        path: '/api/salaryvalue/getById/{id}',
        action: 'get',
        type: RequestMethod.Get
    },
    // 我的月份工资
    mySalary: {
        service,
        controller,
        path: '/api/salaryvalue/mySalary/{month}',
        action: 'mySalary',
        type: RequestMethod.Get
    },
    // 我的工资列表
    mySalaryList: {
        service,
        controller,
        path: '/api/salaryvalue/mySalaryList',
        action: 'mySalaryList',
        type: RequestMethod.Get
    },
    // specify
    specify: {
        service,
        controller,
        path: '/api/salaryvalue/specify',
        action: 'specify',
        type: RequestMethod.Post
    },
    // update
    update: {
        service,
        controller,
        path: '/api/salaryvalue/update',
        action: 'update',
        type: RequestMethod.Post
    }
}
