/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'test'
const service = 'xbt-platform-salary-service'

export const TestController = {
    // 测试分配团队
    update: {
        service,
        controller,
        path: '/api/test/update',
        action: 'update',
        type: RequestMethod.Post
    }
}
