/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { AuthController } from '../../controller/dingtalk-service/auth.controller'

export class AuthService {
    /**
     * 获取AccessToken
     */
    @Request({
        server: AuthController.getAccessToken
    })
    public getAccessToken(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * unionId换取UserId
     */
    @Request({
        server: AuthController.getUserIdByUnionId
    })
    public getUserIdByUnionId(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 钉钉AuthCode登录
     */
    @Request({
        server: AuthController.loginByCode
    })
    public loginByCode(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 钉钉SNS扫码登录
     */
    @Request({
        server: AuthController.loginBySnsCode
    })
    public loginBySnsCode(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
