/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { DepartmentController } from '../../controller/dingtalk-service/department.controller'

export class DepartmentService {
    /**
     * 查询全部
     */
    @Request({
        server: DepartmentController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 查询部门的所有子部门(包含自己)
     */
    @Request({
        server: DepartmentController.getAllChildrenById
    })
    public getAllChildrenById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 查询钉钉的所有部门
     */
    @Request({
        server: DepartmentController.getAllFromDingTalk
    })
    public getAllFromDingTalk(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 查询所有分院
     */
    @Request({
        server: DepartmentController.getBranches
    })
    public getBranches(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 使用ID查询子部门
     */
    @Request({
        server: DepartmentController.getChildrenById
    })
    public getChildrenById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 查询部门详情
     */
    @Request({
        server: DepartmentController.getDepartmentById
    })
    public getDepartmentById(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 查询部分
     */
    @Request({
        server: DepartmentController.getDepts
    })
    public getDepts(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 查询部门所在分院
     */
    @Request({
        server: DepartmentController.getMyBranch
    })
    public getMyBranch(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 同步全部部门
     */
    @Request({
        server: DepartmentController.syncAllDepartment
    })
    public syncAllDepartment(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
