/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { HrmController } from '../../controller/dingtalk-service/hrm.controller'

export class HrmService {
    /**
     * 获取智能人事员工信息按需转换
     */
    @Request({
        server: HrmController.getEmployeeOtherInfo
    })
    public getEmployeeOtherInfo(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取人事字段
     */
    @Request({
        server: HrmController.getHrmEmployeeField
    })
    public getHrmEmployeeField(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取智能人事员工信息
     */
    @Request({
        server: HrmController.getHrmEmployeeInfo
    })
    public getHrmEmployeeInfo(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
