/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { Employee_attendanceController } from '../../controller/salary-service/employee_attendance.controller'

export class Employee_attendanceService {
    /**
     * get All
     */
    @Request({
        server: Employee_attendanceController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: Employee_attendanceController.getByEmployee
    })
    public getByEmployee(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: Employee_attendanceController.get
    })
    public get(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * import excel
     */
    @Request({
        server: Employee_attendanceController.import
    })
    public import(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * update
     */
    @Request({
        server: Employee_attendanceController.update
    })
    public update(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
