/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { Inner_rewardController } from '../../controller/salary-service/inner_reward.controller'

export class Inner_rewardService {
    /**
     * 申请
     */
    @Request({
        server: Inner_rewardController.apply
    })
    public apply(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 确认
     */
    @Request({
        server: Inner_rewardController.confirm
    })
    public confirm(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * create
     */
    @Request({
        server: Inner_rewardController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * delete
     */
    @Request({
        server: Inner_rewardController.delete
    })
    public delete(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 驳回
     */
    @Request({
        server: Inner_rewardController.deny
    })
    public deny(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 导出待审批
     */
    @Request({
        server: Inner_rewardController.exportTodo
    })
    public exportTodo(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get All
     */
    @Request({
        server: Inner_rewardController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 审批历史
     */
    @Request({
        server: Inner_rewardController.getAuditList
    })
    public getAuditList(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: Inner_rewardController.get
    })
    public get(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 审批内容
     */
    @Request({
        server: Inner_rewardController.getAllConfirm
    })
    public getAllConfirm(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get List
     */
    @Request({
        server: Inner_rewardController.getList
    })
    public getList(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 我的流程规则
     */
    @Request({
        server: Inner_rewardController.getMyFlowConfig
    })
    public getMyFlowConfig(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 我的所有申请
     */
    @Request({
        server: Inner_rewardController.getMyList
    })
    public getMyList(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 我的审批流程
     */
    @Request({
        server: Inner_rewardController.getMySalaryConfirmFlow
    })
    public getMySalaryConfirmFlow(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * update
     */
    @Request({
        server: Inner_rewardController.update
    })
    public update(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
