/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { MonthBonusController } from '../../controller/salary-service/month-bonus.controller'

export class MonthBonusService {
    /**
     * create
     */
    @Request({
        server: MonthBonusController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * delete
     */
    @Request({
        server: MonthBonusController.delete
    })
    public delete(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * getDetail
     */
    @Request({
        server: MonthBonusController.getDetail
    })
    public getDetail(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * import excel
     */
    @Request({
        server: MonthBonusController.import
    })
    public import(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * updateDomain
     */
    @Request({
        server: MonthBonusController.updateDomain
    })
    public updateDomain(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
