/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { Period_checkController } from '../../controller/salary-service/period_check.controller'

export class Period_checkService {
    /**
     * get All
     */
    @Request({
        server: Period_checkController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne by employee
     */
    @Request({
        server: Period_checkController.getByEmployee
    })
    public getByEmployee(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: Period_checkController.get
    })
    public get(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * getList of detail
     */
    @Request({
        server: Period_checkController.getDetailListByEmployee
    })
    public getDetailListByEmployee(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
