/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { ReportController } from '../../controller/salary-service/report.controller'

export class ReportService {
    /**
     * 导出列表
     */
    @Request({
        server: ReportController.exportAnalysis
    })
    public exportAnalysis(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 导出审批记录
     */
    @Request({
        server: ReportController.exportAudit
    })
    public exportAudit(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 导出列表
     */
    @Request({
        server: ReportController.exportDetail
    })
    public exportDetail(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 导出个人总计
     */
    @Request({
        server: ReportController.exportEmployeeSummary
    })
    public exportEmployeeSummary(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 部门总计
     */
    @Request({
        server: ReportController.query
    })
    public query(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
