/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { Salary_informController } from '../../controller/salary-service/salary_inform.controller'

export class Salary_informService {
    /**
     * 员工确认
     */
    @Request({
        server: Salary_informController.confirm
    })
    public confirm(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 员工否认
     */
    @Request({
        server: Salary_informController.deny
    })
    public deny(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 多人下发
     */
    @Request({
        server: Salary_informController.informList
    })
    public informList(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 单人下发
     */
    @Request({
        server: Salary_informController.inform
    })
    public inform(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
