/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { Salary_confirm_flowController } from '../../controller/salary-service/salary_confirm_flow.controller'

export class Salary_confirm_flowService {
    /**
     * 审核同意
     */
    @Request({
        server: Salary_confirm_flowController.confirm
    })
    public confirm(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 创建审批
     */
    @Request({
        server: Salary_confirm_flowController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 审核不同意
     */
    @Request({
        server: Salary_confirm_flowController.deny
    })
    public deny(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 审批列表
     */
    @Request({
        server: Salary_confirm_flowController.getAllConfirm
    })
    public getAllConfirm(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 我的流程
     */
    @Request({
        server: Salary_confirm_flowController.getList
    })
    public getList(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
