/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { Social_securityController } from '../../controller/salary-service/social_security.controller'

export class Social_securityService {
    /**
     * export excel
     */
    @Request({
        server: Social_securityController.export
    })
    public export(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get All
     */
    @Request({
        server: Social_securityController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: Social_securityController.get
    })
    public get(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * import excel
     */
    @Request({
        server: Social_securityController.import
    })
    public import(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
