/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { SysdictController } from '../../controller/salary-service/sysdict.controller'

export class SysdictService {
    /**
     * get All
     */
    @Request({
        server: SysdictController.getAll
    })
    public getAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * findOne
     */
    @Request({
        server: SysdictController.get
    })
    public get(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * get Detail
     */
    @Request({
        server: SysdictController.getDetailAll
    })
    public getDetailAll(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * find Detail One
     */
    @Request({
        server: SysdictController.getDetail
    })
    public getDetail(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
