/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { TestController } from '../../controller/salary-service/test.controller'

export class TestService {
    /**
     * 批量创建一个员工的多月工资条
     */
    @Request({
        server: TestController.batchCreateSalaryValue
    })
    public batchCreateSalaryValue(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 按月返导入
     */
    @Request({
        server: TestController.monthBonusLocalFileImport
    })
    public monthBonusLocalFileImport(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 测试分配团队
     */
    @Request({
        server: TestController.update
    })
    public update(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
