/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { TestController } from '../../controller/salary-service/test.controller'

export class TestService {
    /**
     * 测试分配团队
     */
    @Request({
        server: TestController.update
    })
    public update(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
