/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { Test/salaryvalueController } from '../../controller/salary-service/test/salaryvalue.controller'

export class Test/salaryvalueService {
    /**
     * 生成指定月份工资
     */
    @Request({
        server: Test/salaryvalueController.create
    })
    public create(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 删除指定月份工资
     */
    @Request({
        server: Test/salaryvalueController.delete
    })
    public delete(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
