/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'department'
const service = 'xbt-platform-dingtalk-service'

export const DepartmentController = {
    // 查询全部
    getAll: {
        service,
        controller,
        path: '/api/department/getAll',
        action: 'getAll',
        type: RequestMethod.Get
    },
    // 查询钉钉的所有部门
    getAllWx: {
        service,
        controller,
        path: '/api/department/getAllFromDingTalk',
        action: 'getAllWx',
        type: RequestMethod.Get
    },
    // 查询所有分院
    getBranches: {
        service,
        controller,
        path: '/api/department/getBranches',
        action: 'getBranches',
        type: RequestMethod.Get
    },
    // 使用ID查询子部门
    getChildrenById: {
        service,
        controller,
        path: '/api/department/getChildrenById/{id}',
        action: 'getChildrenById',
        type: RequestMethod.Get
    },
    // 查询部分
    getDepts: {
        service,
        controller,
        path: '/api/department/getDepts/{ids}',
        action: 'getDepts',
        type: RequestMethod.Get
    },
    // 查询部门所在分院
    getMyBranch: {
        service,
        controller,
        path: '/api/department/getMyBranch/{id}',
        action: 'getMyBranch',
        type: RequestMethod.Get
    },
    // 同步全部部门
    syncAllDepartment: {
        service,
        controller,
        path: '/api/department/syncAllDepartment',
        action: 'syncAllDepartment',
        type: RequestMethod.Put
    }
}
