/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'hrm'
const service = 'xbt-platform-dingtalk-service'

export const HrmController = {
    // 获取智能人事员工信息按需转换
    getEmployeeOtherInfo: {
        service,
        controller,
        path: '/api/hrm/getEmployeeOtherInfo/{agentId}',
        action: 'getEmployeeOtherInfo',
        type: RequestMethod.Post
    },
    // 获取人事字段
    getHrmEmployeeField: {
        service,
        controller,
        path: '/api/hrm/getHrmEmployeeField/{agentId}',
        action: 'getHrmEmployeeField',
        type: RequestMethod.Get
    },
    // 获取智能人事员工信息
    getHrmEmployeeInfo: {
        service,
        controller,
        path: '/api/hrm/getHrmEmployeeInfo/{agentId}',
        action: 'getHrmEmployeeInfo',
        type: RequestMethod.Post
    }
}
