/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'test/salaryvalue'
const service = 'xbt-platform-salary-service'

export const Test/salaryvalueController = {
    // 生成指定月份工资
    create: {
        service,
        controller,
        path: '/api/test/salaryvalue/create/{month}',
        action: 'create',
        type: RequestMethod.Get
    },
    // 删除指定月份工资
    delete: {
        service,
        controller,
        path: '/api/test/salaryvalue/delete/{month}',
        action: 'delete',
        type: RequestMethod.Get
    }
}
