/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { RequestMethod } from '@gopowerteam/http-request'

// 控制器名称
const controller = 'test/example/json'
const service = 'xbt-platform-salary-service'

export const Test/example/jsonController = {
    // 核算基数按月返Json
    getMonthBonusRule: {
        service,
        controller,
        path: '/api/test/example/json/monthBonusRule',
        action: 'getMonthBonusRule',
        type: RequestMethod.Get
    },
    // 核算基数MvelJson
    getMvelRuleSource: {
        service,
        controller,
        path: '/api/test/example/json/mvel',
        action: 'getMvelRuleSource',
        type: RequestMethod.Get
    }
}
