/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import type { Observable } from 'rxjs'
import { SMSControllerController } from '../../controller/kyb-service/s-m-s-controller.controller'

export class SMSControllerService {
    /**
     * 发送一个后台不验证的验证码
     */
    @Request({
        server: SMSControllerController.sendSMSCode
    })
    public sendSMSCode(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
