/**
 * This file is generated by the RequestConfigGenerator.
 * Do not edit.
 */
import { Request, RequestParams } from '@gopowerteam/http-request'
import { Observable } from 'rxjs'
import { WxMaControllerController } from '../../controller/kyb-service/wx-ma-controller.controller'

export class WxMaControllerService {
    /**
     * authGet
     */
    @Request({
        server: WxMaControllerController.authGet
    })
    public authGet(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * post
     */
    @Request({
        server: WxMaControllerController.post
    })
    public post(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 获取用户的UnionId
     */
    @Request({
        server: WxMaControllerController.getUnionId
    })
    public getUnionId(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * 授权获取微信用户信息
     */
    @Request({
        server: WxMaControllerController.getWxMpUserInfo
    })
    public getWxMpUserInfo(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * getWxaCodeFile
     */
    @Request({
        server: WxMaControllerController.getWxaCodeFile
    })
    public getWxaCodeFile(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * getWxaCodeLimitedFile
     */
    @Request({
        server: WxMaControllerController.getWxaCodeLimitedFile
    })
    public getWxaCodeLimitedFile(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
    /**
     * phone
     */
    @Request({
        server: WxMaControllerController.phone
    })
    public phone(requestParams: RequestParams): Observable<any> {
        return requestParams.request()
    }
}
